# -*- coding: utf-8 -*-
"""See caitlin countdown.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sILDAtI6Zo0bpAAXoTb4j0tGVABEubGL
"""

from datetime import datetime, timezone
from zoneinfo import ZoneInfo
import streamlit as st
import streamlit.components.v1 as components

# ---------- Config ----------
st.set_page_config(page_title="Countdown", page_icon="🌸", layout="centered")

TZ_CENTRAL = ZoneInfo("America/Chicago")
TARGET = datetime(2026, 7, 5, 15, 0, 0, tzinfo=TZ_CENTRAL)
target_utc_ms = int(TARGET.astimezone(timezone.utc).timestamp() * 1000)

html = f"""
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  html, body {{
    height: 100%;
    margin: 0;
    padding: 0;
    overflow: hidden;
    font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
  }}

  body {{
    background: linear-gradient(135deg, #ffd6e8, #ffeef6);
  }}

  /* Flowers layer */
  .flowers {{
    position: fixed;
    inset: 0;
    pointer-events: none;
    z-index: 1;
  }}

  .flower {{
    position: absolute;
    font-size: 32px;
    opacity: 0.6;
    pointer-events: auto; /* clickable */
    cursor: pointer;
    user-select: none;
    animation: float 18s linear infinite;
    filter: drop-shadow(0 6px 10px rgba(255, 105, 180, 0.22));
    will-change: transform, opacity;
  }}

  @keyframes float {{
    0%   {{ transform: translate3d(0,110vh,0) rotate(0deg); }}
    100% {{ transform: translate3d(0,-10vh,0) rotate(360deg); }}
  }}

  /* Center content */
  .wrap {{
    position: fixed;
    inset: 0;
    display: grid;
    place-items: center;
    z-index: 2;
    padding: 16px;
  }}

  .timer-box {{
    background: rgba(255, 255, 255, 0.75);
    backdrop-filter: blur(10px);
    border-radius: 24px;
    padding: 30px 20px;
    box-shadow: 0 10px 30px rgba(255, 105, 180, 0.25);
    text-align: center;
    width: min(920px, 92vw);
  }}

  .timer-text {{
    font-size: 52px;
    font-weight: 800;
    letter-spacing: 1px;
    color: #b03060;
    line-height: 1.15;
  }}

  .subtitle {{
    font-size: 20px;
    color: #a8326d;
    margin-bottom: 10px;
  }}

  @media (max-width: 520px) {{
    .timer-text {{ font-size: 40px; }}
    .subtitle {{ font-size: 18px; }}
  }}

  /* Burst particles */
  .burst {{
    position: fixed;
    width: 10px;
    height: 10px;
    border-radius: 999px;
    pointer-events: none;
    z-index: 9999;
    opacity: 0.95;
    will-change: transform, opacity;
    animation: burst-move 520ms ease-out forwards;
  }}

  @keyframes burst-move {{
    0%   {{ transform: translate3d(0,0,0) scale(1); opacity: 0.95; }}
    100% {{ transform: translate3d(var(--dx), var(--dy), 0) scale(0.2); opacity: 0; }}
  }}
</style>
</head>

<body>
  <div class="flowers" id="flowers"></div>

  <div class="wrap">
    <div class="timer-box">
      <div class="subtitle">💗 Countdown to a HUGGY WUGGY 💗</div>
      <div class="subtitle">July 5, 2026 — 3:00 PM</div>
      <div class="timer-text" id="timer">Loading…</div>
    </div>
  </div>

<script>
(() => {{
  const TARGET_UTC_MS = {target_utc_ms};
  const layer = document.getElementById("flowers");
  const colors = ["#ff4fa3", "#ff77c8", "#ff9ad9", "#ffb6e6", "#ff2d8f"];

  function pad2(n) {{ return String(n).padStart(2, "0"); }}