# -*- coding: utf-8 -*-
"""See caitlin countdown.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sILDAtI6Zo0bpAAXoTb4j0tGVABEubGL
"""

# app.py
import time
from datetime import datetime, timezone
from zoneinfo import ZoneInfo
import streamlit as st

# --------------------------------------------------
# Page Config
# --------------------------------------------------
st.set_page_config(page_title="Countdown", page_icon="🌸", layout="centered")

TZ_CENTRAL = ZoneInfo("America/Chicago")
TARGET = datetime(2026, 7, 5, 15, 0, 0, tzinfo=TZ_CENTRAL)

# --------------------------------------------------
# Global Background (so login matches too)
# --------------------------------------------------
st.markdown(
    """
<style>
.stApp {
    background: linear-gradient(135deg, #ffd6e8, #ffeef6);
    overflow: hidden;
}
</style>
    """.strip(),
    unsafe_allow_html=True
)

# --------------------------------------------------
# Password Gate (same lock screen)
# --------------------------------------------------
if "unlocked" not in st.session_state:
    st.session_state.unlocked = False

if not st.session_state.unlocked:
    st.markdown(
        """
<div style="text-align:center; margin-top:80px;">
  <div style="font-size:40px; font-weight:800; color:#b03060;">
    Only for Caitlin Fowler 💗
  </div>
  <div style="font-size:18px; color:#a8326d; margin-top:10px;">
    Enter the password to view the countdown
  </div>
</div>
        """.strip(),
        unsafe_allow_html=True
    )

    pw = st.text_input("Password", type="password", placeholder="Type it here…")

    if st.button("Unlock 💗"):
        if pw == "ILY":
            st.session_state.unlocked = True
            st.rerun()
        else:
            st.error("Wrong password 😭")

    st.stop()

# --------------------------------------------------
# CSS ONLY (keep separate so HTML never shows as text)
# --------------------------------------------------
st.markdown(
    """
<style>
/* Floating emojis layer */
.flowers {
    position: fixed;
    inset: 0;
    pointer-events: none;
    z-index: 0;
}

.flower {
    position: absolute;
    font-size: 32px;
    opacity: 0.6;
    animation-name: float;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
}

/* Always spawn from bottom and float up */
@keyframes float {
    0%   { transform: translateY(110vh) rotate(0deg); }
    100% { transform: translateY(-10vh) rotate(360deg); }
}

/* Timer box */
.timer-box {
    background: rgba(255, 255, 255, 0.75);
    backdrop-filter: blur(10px);
    border-radius: 24px;
    padding: 30px 20px;
    box-shadow: 0 10px 30px rgba(255, 105, 180, 0.25);
    text-align: center;
}

.timer-text {
    font-size: 52px;
    font-weight: 800;
    letter-spacing: 1px;
    color: #b03060;
}

.subtitle {
    font-size: 20px;
    color: #a8326d;
    margin-bottom: 10px;
}
</style>
    """.strip(),
    unsafe_allow_html=True
)

# --------------------------------------------------
# FLOWERS HTML ONLY (bottom spawn + continuous + random-feel)
# --------------------------------------------------
st.markdown(
    """
<div class="flowers">
  <!-- More emojis = more continuous flow.
       Random-feel comes from mixed delays + mixed durations (speeds). -->

  <div class="flower" style="left:4%;  animation-delay:0s;  animation-duration:17s;">🌸</div>
  <div class="flower" style="left:9%;  animation-delay:2s;  animation-duration:22s;">🎀</div>
  <div class="flower" style="left:14%; animation-delay:4s;  animation-duration:19s;">🌷</div>
  <div class="flower" style="left:19%; animation-delay:6s;  animation-duration:24s;">🧸</div>
  <div class="flower" style="left:24%; animation-delay:1s;  animation-duration:18s;">🌺</div>
  <div class="flower" style="left:29%; animation-delay:8s;  animation-duration:21s;">💐</div>

  <div class="flower" style="left:34%; animation-delay:3s;  animation-duration:20s;">🎀</div>
  <div class="flower" style="left:39%; animation-delay:10s; animation-duration:25s;">🌸</div>
  <div class="flower" style="left:44%; animation-delay:5s;  animation-duration:18s;">🌷</div>
  <div class="flower" style="left:49%; animation-delay:12s; animation-duration:23s;">🧸</div>
  <div class="flower" style="left:54%; animation-delay:7s;  animation-duration:19s;">🌺</div>
  <div class="flower" style="left:59%; animation-delay:14s; animation-duration:26s;">💐</div>

  <div class="flower" style="left:64%; animation-delay:9s;  animation-duration:17s;">🌸</div>
  <div class="flower" style="left:69%; animation-delay:16s; animation-duration:24s;">🎀</div>
  <div class="flower" style="left:74%; animation-delay:11s; animation-duration:20s;">🌷</div>
  <div class="flower" style="left:79%; animation-delay:18s; animation-duration:27s;">🧸</div>
  <div class="flower" style="left:84%; animation-delay:13s; animation-duration:19s;">🌺</div>
  <div class="flower" style="left:89%; animation-delay:20s; animation-duration:22s;">💐</div>

  <!-- Extra wave so it feels nonstop (still bottom-spawn) -->
  <div class="flower" style="left:7%;  animation-delay:15s; animation-duration:21s;">🎀</div>
  <div class="flower" style="left:22%; animation-delay:17s; animation-duration:18s;">🌸</div>
  <div class="flower" style="left:37%; animation-delay:19s; animation-duration:23s;">🌷</div>
  <div class="flower" style="left:52%; animation-delay:21s; animation-duration:20s;">🧸</div>
  <div class="flower" style="left:67%; animation-delay:23s; animation-duration:26s;">🌺</div>
  <div class="flower" style="left:82%; animation-delay:25s; animation-duration:19s;">💐</div>
</div>
    """.strip(),
    unsafe_allow_html=True
)

# --------------------------------------------------
# Title
# --------------------------------------------------
st.markdown(
    """
<div class="timer-box">
  <div class="subtitle">💗 Countdown to a HUGGY WUGGY 💗</div>
  <div class="subtitle">July 5, 2026 — 3:00 PM</div>
</div>
    """.strip(),
    unsafe_allow_html=True
)

placeholder = st.empty()

# --------------------------------------------------
# Countdown Loop
# --------------------------------------------------
fps = 30
sleep_s = 1 / fps

while True:
    now = datetime.now(timezone.utc)
    delta = TARGET.astimezone(timezone.utc) - now
    total_seconds = delta.total_seconds()

    if total_seconds <= 0:
        placeholder.markdown(
            """
<div class="timer-box">
  <div class="timer-text">🌸 IT’S TIME 🌸</div>
  <div class="subtitle">I’m finally with you 💗</div>
</div>
            """.strip(),
            unsafe_allow_html=True
        )
        st.balloons()
        break

    days = int(total_seconds // 86400)
    rem = total_seconds - days * 86400
    hours = int(rem // 3600)
    rem -= hours * 3600
    minutes = int(rem // 60)
    rem -= minutes * 60
    seconds = int(rem)
    ms = int((rem - seconds) * 1000)

    text = f"{days:02d}d  {hours:02d}h  {minutes:02d}m  {seconds:02d}s  {ms:03d}ms"

    placeholder.markdown(
        f"""
<div class="timer-box">
  <div class="timer-text">{text}</div>
</div>
        """.strip(),
        unsafe_allow_html=True
    )

    time.sleep(sleep_s)